### get all showrooms
GET http://localhost:8080/webapi/showrooms

### get all showrooms with params
GET http://localhost:8080/webapi/showrooms?phrase=carabc
custom-header: custom-value
Cookie: some-cookie=value

### get showroom by id
GET http://localhost:8080/webapi/showrooms/2
Accept: application/xml

### get showroom by car
GET http://localhost:8080/webapi/cars/7/showrooms
Accept: application/json

### create new showroom
POST http://localhost:8080/webapi/showrooms
Content-Type: application/json
Accept-Language: en

{
  "name": "",
  "logo": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Mercedes_benz_logo1989.png"
}